# Base configs
baseurl: "https://www.ynid.ml"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "weibography by Ram Patra"
subtitle: "See the world through my eyes!"
author: "xiaoyigezhe"
header:
 title: "Weibography"
 subtitle: "by Xiao"
footer:
 name: "Hey there, my name is Xiao"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "AJ"
social_urls:
  weibo: "https://weibo.com/u/3088067204"
  twitter: "https://www.twitter.com/syw1725"
theme: jekyll-theme-cayman
